const PLANTS_DATA = [
  {
    id: "fiddle-leaf-fig",
    name: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    type: "Leafy Greens",
    difficulty: "Medium",
    difficultyBadge: "bg-secondary-container/90 text-on-secondary-container",
    light: "Bright Indirect",
    lightIcon: "wb_sunny",
    waterFreq: "Every 7-10 days",
    waterLevel: 45,
    location: "Hallway • Needs heavy watering",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC3_Ro6PTHcbpRIdOqPLcQGSjHzl-mUUf2QyaKOaP-UhrT3sPXHS1f6pW1XSUjK9M1U9R4AEQ8vDgWgjdvtEcpbsx9uJtcC8a5lCOLzKpFpIhXg_I48LSueV1s_LvFTyzzJnam_jVYdOYFzWXvWCnMMTrweFRJo6thgwisTCtkiJtIJ0KZT2yLnOPNsJ7knRR3fq8UWYLMVZ6mIPoIX9NmTMPDAlkSNA4QtruCGmydhz_C3zh4hU33U4ugjSrJhdtJ7yjzWVZI6eLAc",
    description: "Famous for its huge, glossy fiddle-shaped leaves. Requires bright filtered light and consistent moisture without waterlogging.",
    soil: "Well-draining peat mix with perlite",
    humidity: "High (50-65%)",
    temp: "65°F - 75°F (18°C - 24°C)",
    toxicToPets: true,
    wateredToday: false
  },
  {
    id: "snake-plant",
    name: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    type: "Succulents",
    difficulty: "Easy",
    difficultyBadge: "bg-primary-container/90 text-on-primary-container",
    light: "Low Light",
    lightIcon: "cloudy_snowing",
    waterFreq: "Every 2-3 weeks",
    waterLevel: 80,
    location: "Bedroom • Drought tolerant",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAxsvuSOfRvP0uUDk-nkf1NfPF0xA92xvvq351rJ6zyeV2D0f-Ty6XHbpeYtn8MbhLvbCRI9-lD_tutmDd5YDVdumTwZJr-76esB8QeBv3uF8AAhwbGgFNgdc8ksW4Y1KaA8X_1yP6UZdTqTFfpNED1m4rMpM_zjpmQBzQQF7jnnUnO0EqEew4XOPvZzIO6JB9EnPtqzGAIwA-8jWont3ELdZLdM2zdamOhFRXTdegPaZUX4palw7sH1IggzuEZQLU1YVYb2Au8yjcd",
    description: "Nearly indestructible, upright architectural plant that thrives in almost any lighting condition and purifies indoor air.",
    soil: "Cactus & succulent coarse mix",
    humidity: "Low to Moderate (30-50%)",
    temp: "55°F - 85°F (13°C - 29°C)",
    toxicToPets: true,
    wateredToday: true
  },
  {
    id: "monstera-deliciosa",
    name: "Monstera Deliciosa",
    scientificName: "Swiss Cheese Plant",
    type: "Leafy Greens",
    difficulty: "Medium",
    difficultyBadge: "bg-secondary-container/90 text-on-secondary-container",
    light: "Indirect Light",
    lightIcon: "sunny",
    waterFreq: "Every 1-2 weeks",
    waterLevel: 65,
    location: "Living Room • Air purifying",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDX3H-6NpUivwtYjwlP8lWU8MW8Qh4Ln_9pwozsvBRxLXdzbIt5SOKKTXQ8VnU5SLlBfeaJTMP1jHdngIQqy1sV6-mmBBq-fPWYk6LgDKV8VVgPbTKvx0UuLL4H0o9gbX2yjXSP6XL_38QZa928ssamSKdIFEiMnJYwHmAOrUwoRhtK2ejHvdxQt6nWrM89HJQ0p5arBrgxSSQkt2uRVzOcwv20IQ3XAStyRVIpvfSlXW6FoM2YnsMKu-1YPvXnxtuxMsd088wzgWCo",
    description: "Iconic tropical plant celebrated for its natural leaf splits (fenestrations) and climbing vine habit.",
    soil: "Rich organic potting soil mix with orchid bark",
    humidity: "Medium to High (60%+)",
    temp: "68°F - 86°F (20°C - 30°C)",
    toxicToPets: true,
    wateredToday: false
  },
  {
    id: "string-of-pearls",
    name: "String of Pearls",
    scientificName: "Curio rowleyanus",
    type: "Succulents",
    difficulty: "Hard",
    difficultyBadge: "bg-tertiary-container/90 text-on-tertiary-container",
    light: "Bright Light",
    lightIcon: "wb_sunny",
    waterFreq: "Every 2 weeks",
    waterLevel: 30,
    location: "Window Sill • Hanging planter",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD3hOPAZHb8H-2raVysRVNPZZIHz3WTQqAyc7uioddwAkcL-Uq-PwJoyj6JyZsNXm4Y7OsvSTeG-zcbfUNMFE0nHp2g2SQT2th-uYmRN7ZbFx_rlnOHdAsW1Ti1P-ko1r2XeBymDgiH2oGb66Ot4jl9Xa7ZRyFD9ZvvZ5DExS-99RpwZw_bmkD3uFr14Jp76pK5xuu2KHN2sjucPYewdWWhiRZ57RXHhLBt_PrUPMAQYbgaZm5Vpxy23UGDulkiwjrfJKWMWuhDAQRB",
    description: "Cascading succulent featuring tiny spherical green 'pearl' leaves that store water efficiently.",
    soil: "Gritty fast-draining succulent substrate",
    humidity: "Low (40% or lower)",
    temp: "70°F - 80°F (21°C - 27°C)",
    toxicToPets: true,
    wateredToday: false
  },
  {
    id: "peace-lily",
    name: "Peace Lily",
    scientificName: "Spathiphyllum",
    type: "Flowering",
    difficulty: "Easy",
    difficultyBadge: "bg-primary-container/90 text-on-primary-container",
    light: "Moderate Light",
    lightIcon: "partly_cloudy_day",
    waterFreq: "Every 5-7 days",
    waterLevel: 25,
    location: "Dining Room • Moisture lover",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDV9eupTJjnKGDZokQgebLPqWrALLXhrkkSzCIvuBKis-fQW6I0Te_Q9emnxlxA02Bc-waDjjcX8JuyLmSKm5WY79zLP1Ct-9Vw9ZBf984vbkY2fZ9AVD0fvR8XFGQRThErHlwrjTW5urWqI88Ap5F-xcocU3btZifwaZzLqvUVBocx5xPyuo467BsllvDQhxiE72wDXzcyKJfWqteS9D_6aAvvQXSFeuxtpGPz3aBvS2yhRhFl7TWEZjRGYuQRY0yMaUslPQ4HR8PY",
    description: "Graceful indoor bloomer producing elegant white spathes. Tells you when it's thirsty by dramatically drooping its leaves.",
    soil: "Moisture-retentive, loose potting mix",
    humidity: "High (60%+)",
    temp: "65°F - 80°F (18°C - 27°C)",
    toxicToPets: true,
    wateredToday: false
  },
  {
    id: "echeveria",
    name: "Echeveria Rosette",
    scientificName: "Echeveria elegans",
    type: "Succulents",
    difficulty: "Easy",
    difficultyBadge: "bg-primary-container/90 text-on-primary-container",
    light: "Full Sun",
    lightIcon: "wb_sunny",
    waterFreq: "Every 10-14 days",
    waterLevel: 90,
    location: "Balcony / Sunny Deck",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDdE9Fmh6gC7eEwPE5EdVpIRlbWksAVaJNLbQ0ngSKHIrtooCvBpE9BqV-lVJf0B8cvDwVAluLPESxUAIkJ8mCmW5tP89kXy06g4QBlxOf4y2CokfoZ8xdZSu8jiDKJ_6sanhgrcxGnjcSU9nx35ZZQyqV0bdBZ4wNUS1o5FphBz93x1CW9cXdRBZ1ZmFumF5u78yuUL4ifAJ_yGg_iOXiSTSU-AU4zcao3aLV5T_SklZYBF74zvrJZys5qHxfVTXF7t-qMvnktAKX0",
    description: "Charming stone-like succulent rosettes with powdery pastel edges. Compact, sun-loving, and extremely low maintenance.",
    soil: "Sand and coarse perlite succulent mix",
    humidity: "Low (30-40%)",
    temp: "60°F - 80°F (15°C - 27°C)",
    toxicToPets: false,
    wateredToday: true
  },
  {
    id: "calathea-ornata",
    name: "Calathea Ornata",
    scientificName: "Pinstripe Calathea",
    type: "Tropical",
    difficulty: "Hard",
    difficultyBadge: "bg-tertiary-container/90 text-on-tertiary-container",
    light: "Indirect Light",
    lightIcon: "partly_cloudy_day",
    waterFreq: "Every 4-5 days",
    waterLevel: 20,
    location: "Bedroom Shelf • High humidity",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA9oZDGRFd1skTAngrQQR0vkohgJUNPosORZxukLT2QzkJ_GcryyPPnKxKh7RqdmzH0p1CFPxHo4h0pnVZKLbcCZkY2WlhwKLK2tl1k1Rxjnv6bOB7o9i7tJz-__9K7zV6kEttplWVX_rkpmJ1jWr833eiD03z_cGZx2z-xx4n-gqYzRR-_1HxHD68ELeoH2oeTvb0OBv1lhA2isHmr3kCpshKUlHXYf8XfCkznWC4ZMkyseVtJyJzg5BGRv-LjsPRwfbADlqN1jxoD",
    description: "Stunning prayer plant adorned with delicate pink pinstripes on deep emerald green leaves. Folds leaves upward at night.",
    soil: "Rich, aerated peat & sphagnum mix",
    humidity: "Very High (65-80%)",
    temp: "65°F - 75°F (18°C - 24°C)",
    toxicToPets: false,
    wateredToday: false
  },
  {
    id: "golden-pothos",
    name: "Golden Pothos",
    scientificName: "Epipremnum aureum",
    type: "Leafy Greens",
    difficulty: "Easy",
    difficultyBadge: "bg-primary-container/90 text-on-primary-container",
    light: "Low to Bright",
    lightIcon: "cloudy_snowing",
    waterFreq: "Every 7-10 days",
    waterLevel: 85,
    location: "Living Room • Hanging Basket",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAnZvgjTflA_SXJ5iZax2MCpgnh7HALHziOJ9v9G0DX0fv5H0zp8AYBk1iTtcPwQXMhjTCg-vk1wVFKuv6dofWYsxi4QZnaelg8vFNfVF5CGvGBimHej3raICDZTt-sIs6XLPYAhgPySPKKkXyJo-pD5v3nfWB-1jcgBe5fABi9B0AEVFdU_zDquXpql3GsjewlrBXoJB8y1oEvywSrMM_jE5CxzhK9ayuNA5r9YDh2BYR89D8Z1N077_taQrDiFa-X6LFM8k5BYwqU",
    description: "Fast-growing vine with golden-variegated heart-shaped leaves. Adapts effortlessly to virtually any room condition.",
    soil: "Standard all-purpose potting soil",
    humidity: "Moderate (40-60%)",
    temp: "60°F - 85°F (15°C - 29°C)",
    toxicToPets: true,
    wateredToday: true
  },
  {
    id: "bird-of-paradise",
    name: "Bird of Paradise",
    scientificName: "Strelitzia nicolai",
    type: "Tropical",
    difficulty: "Medium",
    difficultyBadge: "bg-secondary-container/90 text-on-secondary-container",
    light: "Full Sun",
    lightIcon: "wb_sunny",
    waterFreq: "Every 5-7 days",
    waterLevel: 35,
    location: "Sunroom • Statement plant",
    image: "https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&w=800&q=80",
    description: "Majestic banana-like leaves that bring instant tropical atmosphere to bright spaces.",
    soil: "Rich, fertile, well-drained loam mix",
    humidity: "High (60%+)",
    temp: "65°F - 80°F (18°C - 27°C)",
    toxicToPets: true,
    wateredToday: false
  },
  {
    id: "aloe-vera",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis",
    type: "Succulents",
    difficulty: "Easy",
    difficultyBadge: "bg-primary-container/90 text-on-primary-container",
    light: "Bright Indirect",
    lightIcon: "sunny",
    waterFreq: "Every 2-3 weeks",
    waterLevel: 75,
    location: "Kitchen Counter",
    image: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=800&q=80",
    description: "Medicinal succulent filled with soothing gel. Needs minimal watering and strong sunlight.",
    soil: "Cactus & succulent mix with grit",
    humidity: "Low (30-40%)",
    temp: "55°F - 80°F (13°C - 27°C)",
    toxicToPets: true,
    wateredToday: true
  },
  {
    id: "zz-plant",
    name: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    type: "Leafy Greens",
    difficulty: "Easy",
    difficultyBadge: "bg-primary-container/90 text-on-primary-container",
    light: "Low Light",
    lightIcon: "cloudy_snowing",
    waterFreq: "Every 3-4 weeks",
    waterLevel: 95,
    location: "Home Office • Shade tolerant",
    image: "https://images.unsplash.com/photo-1637967886160-fd78dc3ce3f5?auto=format&fit=crop&w=800&q=80",
    description: "Features thick waxy dark green stems. Stores water in tuberous rhizomes, making it highly drought resilient.",
    soil: "Standard potting mix with pumice",
    humidity: "Any level (30-60%)",
    temp: "60°F - 85°F (15°C - 29°C)",
    toxicToPets: true,
    wateredToday: true
  },
  {
    id: "boston-fern",
    name: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    type: "Tropical",
    difficulty: "Medium",
    difficultyBadge: "bg-secondary-container/90 text-on-secondary-container",
    light: "Indirect Light",
    lightIcon: "partly_cloudy_day",
    waterFreq: "Every 3-4 days",
    waterLevel: 15,
    location: "Bathroom • High moisture",
    image: "https://images.unsplash.com/photo-1599598425947-434458f00494?auto=format&fit=crop&w=800&q=80",
    description: "Classic feathery fern with arching fronds. Thrives in humid bathrooms or shaded porch settings.",
    soil: "Peat-based potting mix with organic matter",
    humidity: "High (70%+)",
    temp: "60°F - 75°F (15°C - 24°C)",
    toxicToPets: false,
    wateredToday: false
  }
];
